@include('Admin/header')

@yield('home')
@yield('category')
@yield('subcategory')
@yield('service')
@yield('updatecategory')
@yield('updatesubcategory')
@yield('professional')
@yield('coupon')
@yield('booking')
@yield('updatecoupon')
@yield('membership')

@include('Admin/footer')
@yield('script')
@yield('script2')